# Generated by Django 3.2.3 on 2021-07-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.AddField(
            model_name='fcm_tokens',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joker.userss'),
            preserve_default=False,
        ),
    ]
