# Generated by Django 3.2.3 on 2021-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joker', '0002_auto_20210709_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_name', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
