# Generated by Django 3.2.3 on 2021-07-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joker', '0003_highscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighScore',
        ),
    ]
