# Generated by Django 3.2.3 on 2021-07-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='place',
            new_name='city',
        ),
        migrations.AddField(
            model_name='info',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='working_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
